server:
  port: 8888
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/um_system
    username: root
    password: 0531cwt.
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    default-property-inclusion: always
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: delFlag
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: auto
